webtalk_init -webtalk_dir E:/Labs/COAProj/MiniMIPS32_Ri/CPU/MiniMIPS32.sim/sim_1/behav/xsim/xsim.dir/MiniMIPS32_SYS_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec 15 17:07:44 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "091d9ca6-011a-4437-bf52-c20a4a9083ec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bb1d9b6b857a46b28863b191d55162ea" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "172" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "25" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "846 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "58 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "735" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "32" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "177804_KB" -context "xsim\\usage"
webtalk_transmit -clientid 725871362 -regid "" -xml E:/Labs/COAProj/MiniMIPS32_Ri/CPU/MiniMIPS32.sim/sim_1/behav/xsim/xsim.dir/MiniMIPS32_SYS_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Labs/COAProj/MiniMIPS32_Ri/CPU/MiniMIPS32.sim/sim_1/behav/xsim/xsim.dir/MiniMIPS32_SYS_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Labs/COAProj/MiniMIPS32_Ri/CPU/MiniMIPS32.sim/sim_1/behav/xsim/xsim.dir/MiniMIPS32_SYS_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
